language: r
cache: packages

r:
  - oldrel
  - release
  - devel

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_success: change
    on_failure: change
